pull_request_rules:
  - name: automatic merge for Dependabot pull requests (preview)
    conditions:
      - author=dependabot-preview[bot]
      - base=master
    actions:
      merge:
        method: squash
        strict: true
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - base=master
    actions:
      merge:
        method: squash
        strict: true
